# Author: Two-Six<twopsix@duck.com>

"ui.background" = {bg="acme_bg"}
"ui.text" = "black"
"ui.selection" = {bg="#eeeee8"}
"ui.cursorline" = {bg="acme_bar_bg"}
"ui.statusline" = {fg="black", bg="acme_bar_bg"}
"ui.statusline.inactive" = {fg="black", bg="acme_bar_inactive"}
"ui.virtual" = "indent"
"ui.virtual.ruler" = { bg = "acme_bar_bg" }
"ui.cursor.match" = {bg="acme_bar_bg"}
"ui.cursor" = {bg="cursor", fg="white"}

"ui.linenr" = "#888888"
"ui.linenr.selected" = { fg = "#222222", modifiers = ["bold"] }

#"string" = "red"
#"string" = "#444488"
"string" = "#888888"
"comment" = "#888888"

"ui.help" = {fg="black", bg="acme_bg"}
"ui.popup" = {fg="black", bg="acme_bg"}
"ui.menu" = {fg="black", bg="acme_bg"}
"ui.menu.selected" = {bg="selected"}
"ui.window" = {bg="acme_bg"}

"diagnostic.error" = {bg="white", modifiers=["bold"]}
"diagnostic.warning" = {bg="white", modifiers=["bold"]}
"diagnostic.hint" = {bg="white", modifiers=["bold"]}

#"type" = "#008800"
#"type.builtin" = "red"
#"type.enum.variant" = "red"
#"keyword" = "blue"
"keyword" = { fg = "#0022dd" }
#"keyword.control.function" = {fg="#0022dd", modifiers=["bold"]}
#"keyword.function" = {fg="#0022dd", modifiers=["bold"]}

[palette]
white = "#ffffff"
#acme_bg = "#ffffea"
acme_bg = "#ffffff"
black = "#000000"
#selected = "#eeee9e"
##888888 = "#eeee9e"
#acme_bar_bg = "#aeeeee"
acme_bar_bg = "#eeeee8"
acme_bar_inactive = "#eaffff"
cursor = "#444444"
red = "#a0342f"
green = "#065905"
indent = "#aaaaaa"

blue = "#007acc"
blue2 = "#569CD6"
blue3 = "#6796E6"

light_blue = "#75beff"
dark_blue = "#264f78"
dark_blue2 = "#094771"
